name: Build ELS Plus
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1
       
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
     
    - name: Restore NuGet Packages
      run: nuget restore .\src\elsplus.sln
 
    - name: Build and Publish Web App
      run: msbuild .\src\elsplus.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile